# Generated by Django 5.1.2 on 2024-10-29 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_parent'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filetype',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document')], max_length=10),
        ),
    ]
